spring:
  application:
    name: spring-data-parse
  datasource:
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  artemis:
    mode: native
    broker-url: tcp://127.0.0.1:61616
    user: artemis
    password: artemis

app:
  jms:
    queue: app.messages

logging:
  level:
    root: INFO
    org.acme.parse: INFO
