spring:
  application:
    name: producer-xml
  artemis:
    mode: native
    broker-url: ${ARTEMIS_BROKER_URL:tcp://127.0.0.1:61616}
    user: ${ARTEMIS_USER:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  jms:
    pub-sub-domain: true

server:
  port: ${SERVER_PORT:8080}

app:
  jms:
    topic: app.messages.xml

logging:
  level:
    root: INFO
    org.acme.parse: INFO
